name: States
version: '${project.version}'
main: ru.calvian.state.States
api-version: '1.20'
commands:
  p:
    description: Player command
  c:
    description: City command
  s:
    description: State command
  a:
    description: Alliance command