name: States
version: '${project.version}'
main: ru.totalcraftmc.statesplugin.StatesPlugin
api-version: '1.19'
commands:
  player:
    aliases: p
    description: Player command
  city:
    aliases: c
    description: City command
  s:
    description: State command
  a:
    description: Alliance command