name: States
version: '${project.version}'
main: ru.calvian.state.States
api-version: '1.20'
commands:
  player:
    aliases: p
    description: Player command
  city:
    aliases: c
    description: City command
  s:
    description: State command
  a:
    description: Alliance command