name: States
version: '${project.version}'
main: ru.calvian.state.States
api-version: '1.20'
commands:
  player:
    description: Player command
  city:
    description: City command
  state:
    description: State command
  alliance:
    description: Alliance command